# Generated by Django 4.1 on 2022-12-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hall_layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.IntegerField(unique=True, verbose_name='Номер стола')),
                ('number_of_seats', models.IntegerField(verbose_name='Количество мест')),
                ('shape', models.CharField(choices=[('R', 'rectangular'), ('O', 'oval')], max_length=30, verbose_name='Форма')),
                ('horizontal_coordinates', models.IntegerField(verbose_name='Кординаты горизонталь')),
                ('vertical_coordinates', models.IntegerField(verbose_name='Кординаты вертикаль')),
                ('size_width', models.IntegerField(verbose_name='Размер ширина')),
                ('size_length', models.IntegerField(verbose_name='Размер длина')),
            ],
            options={
                'verbose_name': 'Схема зала',
                'verbose_name_plural': 'Схемы зала',
            },
        ),
    ]
