# Generated by Django 4.1 on 2022-12-02 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall_layout',
            name='shape',
            field=models.CharField(choices=[('П', 'прямоугольный'), ('О', 'овальный')], max_length=30, verbose_name='Форма'),
        ),
        migrations.CreateModel(
            name='order_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.hall_layout')),
            ],
        ),
    ]
