# Generated by Django 4.1 on 2022-12-02 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_hall_layout_shape_order_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_list',
            name='table',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.hall_layout'),
        ),
    ]
