# Generated by Django 4.1 on 2022-12-02 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_order_list_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_list',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.hall_layout'),
        ),
    ]
