# Generated by Django 4.1 on 2022-12-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_order_list_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order_list',
            options={'verbose_name': 'Cписок заказов', 'verbose_name_plural': 'Cписок заказов'},
        ),
        migrations.AddField(
            model_name='order_list',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order_list',
            name='name',
            field=models.CharField(max_length=120, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='order_list',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
