# Generated by Django 4.1 on 2022-12-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_order_list_options_order_list_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_list',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
