# Generated by Django 4.1 on 2022-12-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_order_list_date_time_alter_order_list_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_list',
            name='phone_number',
            field=models.CharField(max_length=50, verbose_name='Номер телефона'),
        ),
    ]
