# Generated by Django 4.1 on 2022-12-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_order_list_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_list',
            name='date_time',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='table',
            field=models.IntegerField(verbose_name='Номер столика'),
        ),
    ]
