# Generated by Django 4.1 on 2022-12-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_order_list_date_time_alter_order_list_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tidings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название статьи')),
                ('content', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_upate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '...',
                'verbose_name_plural': '...',
            },
        ),
        migrations.DeleteModel(
            name='hall_layout',
        ),
        migrations.DeleteModel(
            name='order_list',
        ),
    ]
